[package]
name = "safe_real_basic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rkyv= {version= "0.7.10", features=["validation"]}
bytecheck="0.6"